# Generated by Django 5.1.6 on 2025-03-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin')], default='admin_manager', max_length=50),
        ),
    ]
