# Generated by Django 5.1.6 on 2025-03-15 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Staff_Assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Staff_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
