# Generated by Django 5.1.6 on 2025-03-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_alter_customer_staff_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
