# Generated by Django 5.1.6 on 2025-03-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0006_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
