# Generated by Django 5.1.6 on 2025-03-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0015_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('staff', 'Staff'), ('Reseller', 'Reseller')], default='admin_manager', max_length=50),
        ),
    ]
