# Generated by Django 5.1.6 on 2025-03-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0016_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Email_id',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
